export type Cart = {
	size: string;
	count: number;
	product: Product;
};

export type Product = {
	slug: string;
	name: string;
	description: string;
	sizes: string[];
	imageUrls: string[];
	imageBlurhashUrl?: string[]; // Generated by SSR
	categories: string[];
	variations: string[];
	price: {
		amount: number;
		currency: '$';
	};
};

export const baseProducts: Product[] = [
	// Tops
	{
		slug: 'heavy-tshirt',
		name: 'Heavy T-Shirt',
		description: 'A premium heavy t-shirt, perfect for cooler weather.',
		sizes: ['S', 'M', 'L', 'XL'],
		imageUrls: ['products/heavy-tshirt.png'],
		categories: ['Tops'],
		variations: [],
		price: { amount: 30, currency: '$' }
	},
	{
		slug: 'top',
		name: 'Stylish Top',
		description: 'A lightweight and trendy top for casual outings.',
		sizes: ['S', 'M', 'L', 'XL'],
		imageUrls: ['products/top.png'],
		categories: ['Tops'],
		variations: [],
		price: { amount: 35, currency: '$' }
	},
	{
		slug: 'multiple-tshirts',
		name: 'Multiple T-Shirts',
		description: 'A set of colorful t-shirts, perfect for all seasons.',
		sizes: ['S', 'M', 'L', 'XL'],
		imageUrls: ['products/multiple-tshirts.png'],
		categories: ['Tops'],
		variations: [],
		price: { amount: 60, currency: '$' }
	},

	// Sweaters
	{
		slug: 'sweatshirts',
		name: 'Sweatshirts',
		description: 'Warm and cozy sweatshirts for chilly days.',
		sizes: ['S', 'M', 'L', 'XL'],
		imageUrls: ['products/sweatshirts.png'],
		categories: ['Sweaters'],
		variations: [],
		price: { amount: 45, currency: '$' }
	},

	// Shoes
	{
		slug: 'gray-shoes',
		name: 'Gray Shoes',
		description: 'Stylish and comfortable gray shoes for any occasion.',
		sizes: ['6', '7', '8', '9', '10'],
		imageUrls: ['products/gray-shoes.png'],
		categories: ['Shoes'],
		variations: [],
		price: { amount: 70, currency: '$' }
	},
	{
		slug: 'black-shoes',
		name: 'Black Shoes',
		description: 'Classic black shoes for both casual and formal occasions.',
		sizes: ['6', '7', '8', '9', '10'],
		imageUrls: ['products/shoes-black.png'],
		categories: ['Shoes'],
		variations: [],
		price: { amount: 75, currency: '$' }
	},
	{
		slug: 'hanging-shoes',
		name: 'Hanging Shoes',
		description: 'Durable shoes for everyday adventures.',
		sizes: ['6', '7', '8', '9', '10'],
		imageUrls: ['products/hanging-shoes.png'],
		categories: ['Shoes'],
		variations: [],
		price: { amount: 65, currency: '$' }
	},
	{
		slug: 'shoes',
		name: 'Casual Shoes',
		description: 'Comfortable casual shoes for everyday wear.',
		sizes: ['6', '7', '8', '9', '10'],
		imageUrls: ['products/shoes.png'],
		categories: ['Shoes'],
		variations: [],
		price: { amount: 55, currency: '$' }
	},

	// Accessories
	{
		slug: 'black-sunglasses',
		name: 'Black Sunglasses',
		description: 'Classic black sunglasses with UV protection.',
		sizes: ['onesize'],
		imageUrls: ['products/sunglasses-black.png'],
		categories: ['Accessories'],
		variations: [],
		price: { amount: 50, currency: '$' }
	},
	{
		slug: 'aviator-sunglasses',
		name: 'Aviator Sunglasses',
		description: 'Timeless aviator sunglasses with a sleek design.',
		sizes: ['onesize'],
		imageUrls: ['products/sunglasses-aviator.png'],
		categories: ['Accessories'],
		variations: [],
		price: { amount: 65, currency: '$' }
	},
	{
		slug: 'sunglasses',
		name: 'Stylish Sunglasses',
		description: 'Fashionable sunglasses for a sunny day.',
		sizes: ['onesize'],
		imageUrls: ['products/sunglasses.png'],
		categories: ['Accessories'],
		variations: [],
		price: { amount: 55, currency: '$' }
	},
	{
		slug: 'watch',
		name: 'Classic Watch',
		description: 'Elegant and durable watch to complement any outfit.',
		sizes: ['onesize'],
		imageUrls: ['products/watch.png'],
		categories: ['Accessories'],
		variations: [],
		price: { amount: 150, currency: '$' }
	}
];

// Generate 45 Products by Multiplying Base Array
export const products: Product[] = Array.from({ length: 4 }).flatMap((_, index) =>
	baseProducts.map((product) => ({
		...product,
		name: `${product.name} #${index + 1}`
	}))
);
